version: '3.8'

services:
  n8nuploader:
    build: .
    container_name: n8nuploader
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    volumes:
      # Для логов (опционально)
      - ./logs:/app/logs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy (опционально)
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - n8nuploader
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 